const labels = Object.freeze({
    or: 'Or',
    login: 'Log In',
    signup: 'Sign up',
    continueWithGoogle: "Continue with Google",
    typeYourEmail: "Type your email",
    typeYourPassword: "Type your password",
    email: "Email",
    password: "Password",
    rememberMe: "Remember me",
    forgetPassword: "Forget password?",
    dontHaveAnAccount: "Don't have an account?",
    alreadyHaveAnAccount: "Already have an account?",
    phoneNumber: "Phone Number",
    confirmPassword: "Confirm Password",
    userName: "User Name",
    user: "User",
    vendor: "Vendor",
    bookARide: "Book a Ride",
    helloVendor: "Hello Vendor",
    myDashBoard: "My Dashboard",
    addItem: "Add Item",
    orderFood: "Order Food",
    bookYourPlace: "Book Your Place",
    getWhatYoureLookingFor: "Get What You’re",
    lookingForFast: "Looking For–Fast",
    accomodation: "Accommodation",
    stayInComfort: "Stay in Comfort,",
    liveInStyle: "Live in Style",
    stayComfy: "Stay Comfy, Remember Forever",
    searchForAccommodation: "Search for accommodation",
    whatareYouLookingFor: "What are you looking for?",
    singleRoom: "Single Rooms",
    studios: "Studios",
    appartment: "Apartments",
    condos: "Condos",
    hotelRoom: "Hotel Rooms",
    yourNexGateway: "Your Next Getaway",
    parisFrance: "Paris, France",
    oxfordEngland: "Oxford, England",
    newYorkCity: "New York City",
    hotelsForYou: "Hotels for You",
    foodDelivery: "Food Delivery",
    hungryWeHave: "Hungry? We’ve",
    gotYouCovered: "Got you covered",
    riseAndShineBreakfast: "Rise and shine! It's breakfast time",
    whatDoYouWantToEat: "What do you want to eat?",
    nearMe: "Near Me",
    bigPromo: "Big Promo",
    bestSeller: "Best Seller",
    meals: "Meals",
    newlyOpened: "Newly Opened",
    manageRestaurant: "Manage Restaurant",
    manageAccommodation: "Manage Accommodation",
});

export default labels;